server:
  port: 8080

spring:
  application:
    name: notepad-app

  datasource:
    # PostgresQL
    url: jdbc:postgresql://localhost:5432/db-notes
    driverClassName: org.postgresql.Driver
    username: root
    password: password
    # default connection pool
    hikari:
      connectionTimeout=20000
      maximumPoolSize=5
  # update, good for testing, production set to none or comment it
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

